language: node_js
node_js:
  - "8"
install:
  - npm install -g codecov jest
  - npm install babel-preset-env jest-canvas-mock lodash custom-event-polyfill
script:
  - jest --coverage --detectOpenHandles && codecov
